# Generated by Django 5.0.6 on 2024-06-06 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='notified',
            field=models.BooleanField(default=False),
        ),
    ]
